apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  name: devchan-modresortchan-deployment
  namespace: modresort-entitlement
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: modresortchan
    component: main
    package: modresort
    apps.open-cluster-management.io/channel: modresort-devchan ## mandatory
    apps.open-cluster-management.io/channel-type: Namespace ## mandatory
spec:
  channels:
    - modresort-devchan
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: devchan-modresortchan-deployment
      labels:
        app: modresortchan
    spec:
      selector:
        matchLabels:
          app: modresortchan
          release: modresort-devchan
          tier: frontend
      replicas: 1
      template:
        metadata:
          labels:
            app: modresortchan
            release: modresort-devchan
            tier: frontend
        spec:
          containers:
            - name: frontend
              image: "kpostreich/modresort:1.0"
              imagePullPolicy: Always
              ports:
                - containerPort: 9080
              env:
                - name: GET_HOSTS_FROM
                  value: dns
                - name: WLP_LOGGING_CONSOLE_FORMAT
                  value: json
                - name: WLP_LOGGING_CONSOLE_LOGLEVEL
                  value: info
                - name: WLP_LOGGING_CONSOLE_SOURCE
                  value: message,trace,accessLog,ffdc
---
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  name: devchan-modresortchan-service
  namespace: modresort-entitlement
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: modresortchan
    component: main
    package: modresort
    apps.open-cluster-management.io/channel: modresort-devchan ## mandatory
    apps.open-cluster-management.io/channel-type: Namespace ## mandatory
spec:
  channels:
    - modresort-devchan
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: devchan-modresortchan-service
      labels:
        app: modresortchan
    spec:
      type: ClusterIP
      ports:
      -  port: 9080
      selector:
        app: modresortchan
        release: modresort-devchan
        tier: frontend
---
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  name: devchan-modresortchan-route
  namespace: modresort-entitlement
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: modresortchan
    component: main
    package: modresort
    apps.open-cluster-management.io/channel: modresort-devchan ## mandatory
    apps.open-cluster-management.io/channel-type: Namespace ## mandatory
spec:
  channels:
    - modresort-devchan
  template:
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: devchan-modresortchan-route
      name: modresorts
    spec:
      host:
      path: /
      port:
        targetPort: 9080
      to:
        kind: Service
        name: devchan-modresortchan-service
        weight: 100
      wildcardPolicy: None
